from django.db import models
import uuid
# Create your models here.
# Django 自定义 User https://docs.djangoproject.com/en/1.11/topics/auth/customizing/

from django.contrib import auth
auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    # Implicitly remove the autogenerated id column.
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    # A list of the field names that will be prompted for
    # when creating a user via the createsuperuser management command
    # 字段name组成的列表。当创建superuser时用到的字段。
    USERNAME_FIELD = 'email'
    # A string describing the name of the field on the user model
    # that is used as the unique identifier.
    # 必需的。设置认证标识。设置成标识的字段unique必须为True。
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)