# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listuser',
            managers=[
            ],
        ),
    ]
